### ISSUE TITLE
Content Discussion

### ISSUE THREAD

**Issue by mathematicalmichael** [mathematicalmichael/jsm19#3]
Tian:

> 
> Here's my rough idea for what would be good. I was thinking a sort of 3-panel organization with one panel for basic Data Consistent info, one panel for parameter identification, and one panel for solving parameter distribution-type problems under uncertainty. Something like this:
> 
> 
> 1. Parameter ID
> 2. DCI
> 3. Distribution Problems
> 
> I think the overall main idea would be basic theory in the middle, then more example-like stuff on the two side panels.
> 
> One of the goals that I want to get across is how DCI can be used to solve different kinds of problems in comparison to Statistical Bayes. On the param identify panel, it would be nice to show these similarities and differences (I think this panel would be your focus since you have more familiarity with communicating these nuances). On the distribution panel I want to show a comparison between a hierarchical Bayes model and DCI, because I think that is a fair comparison.

- [x] Compare this to the poster right now from CSE and decide what content we want to grab from it.

- [x] Discuss what we mean by "DCI" because from what I understand, this is theory, which belongs before Parameter identification. I think in general, the whole MT framework is just DCI now instead of "Consistent Bayes."

- [x] What are the distribution problems you are thinking about? Are the hierarchical Bayes models where you try to fit sd/mean values for parameters id?

**Comment by mathematicalmichael** [comment]
six segments. 

- [x] theory in middle

- [x] distribution left

- [ ] parameter ID right

- [x] plots broken up by input vs output space, both methods on same plots

- [x] problem setup at top of examples columns

- [x] show equations for the two approaches in the dead middle. 

- [x] middle column: "A Novel Approach" has DCI formula first, then stats, with labels. 

- [x] middle column: "what problem are you trying to solve?" and "what is the difference(s) in the two approaches?" 

> Bayesian Inference updates prior information with a data-likelihood function. 

> Data-Consistent Inversion updates an initial distribution by inverting a measure constructed from data.

- [ ] middle column: model of exponential decay with unknown rate

- [x] middle column: bare minimum necessary notation

- [x] middle column: references

- [x] Title: Using Push-forward and Pull-back Measures for Parameter Identification and Distribution Estimation

**Comment by mathematicalmichael** [comment]
I will go ahead and re-structure the document so that we can have a middle-column `.tex` file and then four more `.tex` files, one for each outer section. 

- [ ] Bayes/DCI Distribution

- [ ] Bayes/DCI Parameter ID

This way, if we decide to swap order (columns have individual methods instead of problem types), we can avoid all copy/pasting.

**Comment by mathematicalmichael** [comment]
Okay... my to-do is to re-structure the poster and get the skeleton of it in place.

**Comment by mathematicalmichael** [comment]
@yentyu 

- [x] bolder lines for plots

- [x] use colors consistent with other notebook figures

- [x] check boxes on github as you go so that we can track things

**Comment by yentyu** [comment]
I did a draft of columns 1 & 2: re-ordering some things and moving figures around.

As a draft, it is more or less finished. Everything that I think should be on the left is there.

@mathematicalmichael: Would you take a look at it sometime on Monday and see if there are any big issues, things that are missing / need to be re-framed or cut?

Otherwise, column 3 and all of the final space adjusting is what is left.

**Comment by mathematicalmichael** [comment]
no big issues, just small things

I pushed them to a new branch called `edits` for your review (`git diff`?) or maybe I'll submit a PR. 

Happy with how your plots look but I would consider grabbing the colors used in my notebook so they match on both sides. I dunno.. just my visual aesthetic nagging at me desiring symmetry. Though the colors you chose are readable. 

- [x] Without moving the location of "Example" on the right, can we somehow make the equations a bit more readable? Font size needs to stay the same, so this is a challenge. [An hour later into learning about latex table formatting and multirow... which I love but have never seen before]: FIXED! Apparently `\hline` is a "hack" ... `\toprule, \midrule, \bottomrule` exist for this sole purpose. I had no idea.... I've always used `\hline`.

- [x] Is "Simple Bayes" really the language?

- [x] not sure what you meant by needs edit, but I assumed you meant that you wanted the full-version of the images (these just had ten samples for expediency), so thats what I changed with respect to images.

- [x] QR code status per #4 ?

**Comment by mathematicalmichael** [comment]
[poster.pdf](https://github.com/mathematicalmichael/jsm19/files/3419456/poster.pdf)

**Comment by yentyu** [comment]
Merged your changes. Thanks for them!

>  Is "Simple Bayes" really the language?

Changed to "Regular Bayes"

> Colors

Couldn't use your colors and get the plots to actually not look horrendous. Ack! Too bad I am bad at color palettes. Gonna ignore this, just for time's sake.

> not sure what you meant by needs edit, but I assumed you meant that you wanted the full-version of the images (these just had ten samples for expediency), so thats what I changed with respect to images.

Convergence of DCI plot is fine.

For the "Comparison to Bayes" plots, we either need to change title or change concept. I thought we were going for the same type of plots but one column was DCI and other column was Stat Bayes (what I am calling regular Bayes). 2 plots in each column, for one for 10 and one for 100 datapoints (ignore 1 and 50). I also liked your sparse plots.

- [ ]  **Can you edit and make the plots with columns which compare DCI is compared to Stat Bayes?**

> QR code status per #4 ?

Continuing discussion in #4 .

**Comment by mathematicalmichael** [comment]
oh wow I actually didn't notice the "Comparison to Bayes" column heading had changed. I literally just replaced the plots with what was there before. Now I think I understand. 

So, I think I understand. Bottom four plots on my end need to be swapped out. 
Two of the four remain (D=10 and 100). Then I simply add the `posterior*.png` images to the figures. Got it. PR forthcoming.


TITLE: We need to be consistent. 
- [x] Pushforward and Pullback 

- [x] Push-Forward and Pull-Back

Does wikipedia have an opinion?

I think the label `P.f. update` has enough room to become `Pushforward`? Should be "pushforward updated" to be grammatically consistent with "predictive"

**Comment by yentyu** [comment]
I merged and made small edits to everything I feel needs editing.

I feel satisfied with everything: if see anything that needs small edits, feel free to make it happen. Otherwise, I think we're done!

- [ ] **Print poster and put it in Tian Yu's office**

**Comment by mathematicalmichael** [comment]
Can I move our names to the bottom? As it is, the title is tooooo squished to the top.

Still have to fix references? 

Also I got it working in a binder with pyMC3 now!

And fixed the `make` errors.

One reference will be to this repo, another to troy's paper, perhaps another to BET.

**Comment by yentyu** [comment]
I thought you already fixed the references. My bad!

I feel a little uncomfortable moving the names to the bottom only, since I
feel like most people will expect to see the names under the title. I am
happy for you to make the names small under the title though, if that makes
more sense!

Thanks Michael!

-Tian Yu

**Comment by mathematicalmichael** [comment]
hmmm.
welll, 1. for some reason the `\color` thing messed up my compilation, so I removed it and am not a fan of how it looks now. That kind of edit should be made in the 	`sty` file. At the very least we should put our university (maybe CU Denver for space) in the same line as authors.

**Comment by mathematicalmichael** [comment]
hmmm.
well, for some reason the `color` thing messed up my compilation, so I removed it and am not a fan of how it looks now. That kind of edit should be made in the `sty` file. At the very least we should put our university (maybe CU Denver for space) in the same line as authors.

**Comment by yentyu** [comment]
Feel free to send me a pdf copy if you want a 2nd pair of eyes.

-Tian Yu

**Comment by mathematicalmichael** [comment]
I'm figuring out printing, seems like I can just walk up to the printer and do it by USB. Will try today, and worst case I can do it in North classroom.

**Comment by yentyu** [comment]
Cool. Thanks!

**Comment by mathematicalmichael** [comment]
[jsm19poster.pdf](https://github.com/mathematicalmichael/jsm19/files/3428662/jsm19poster.pdf)

**Comment by mathematicalmichael** [comment]
wow, caught a lot of spacing things I could improve in < 1 hour
[jsm19poster.pdf](https://github.com/mathematicalmichael/jsm19/files/3428778/jsm19poster.pdf)

THE SYMMETRY IN THE POSTER IS SO ON POINT NOW!!!!

**Comment by yentyu** [comment]
*thumbs up*!
