### ISSUE TITLE
citation QR codes

### ISSUE THREAD

**Issue by mathematicalmichael** [mathematicalmichael/jsm19#4]
https://github.com/fukuchi/libqrencode is what I use to encode citations as QR codes.

- [ ] Decide on key citations (3-4), add to bibtex file

- [ ] Replace current citation images

**Comment by mathematicalmichael** [comment]
added `qrencode` to binder instructions so that QR codes can be generated in Jupyterlab environment using the terminal.

**Comment by mathematicalmichael** [comment]
# Usage
`qrencode website-name -o output.png`

## Help

`qrencode --help`

**Comment by mathematicalmichael** [comment]
@yentyu what are the papers/websites we'll be citing/linking to?

**Comment by yentyu** [comment]
The only things I would reference would be Troy's paper on the Cbayes theory (which I think you've already listed as "theory", right?) and my Master's Thesis... But my Master's isn't really published anywhere. Other than that, I don't have any specific references that I would want to include: most of the rest is original stuff that we are working on but have yet to publish anything.

Thoughts and suggestions?

**Comment by mathematicalmichael** [comment]
I ended up linking to this repo in place of consistentbayes, otherwise the links are the same.
