### ISSUE TITLE
Hierarchical Bayes

### ISSUE THREAD

**Issue by mathematicalmichael** [mathematicalmichael/jsm19#6]
Is it worth pursuing at all?

my thinking is that yes, it would be worth it because....

Since we would be solving for the mean and std of the rate parameter, this is in some sense giving us a "point estimate" and a "description of its uncertainty", answering a fundamentally different question than our other two examples, but providing a solution that can be compared to both! 

A useful thing to find out would be: Given 100 different data realizations (noise realizations), studying stability, what is the _variance_ of the MEANs? how does this compare to 
- variance of the MUD points
- variance of the MAP points
- and how does it change with D=1, 10, 50, 100, data points? 
- accuracy: take the means of the MUDs/MAPs/MEANs and find which is CLOSEST to 0.5

**Comment by mathematicalmichael** [comment]
@yentyu did we decide to include this in the poster or not? 
I don't have any examples anywhere near this at the moment.

**Comment by yentyu** [comment]
I have been working on a notebook for this the last week or so. It is almost done. The analysis is easy to run but requires pymc3--which is a pain to figure out and install the right dependencies. I will push it tonight so you can look at it, but don't spend time trying to get everything to run: I'll try and export the figures tomorrow evening when I finalize what I want to display.

**Note:** I am tired and not sure I read this correctly--I think we should pursue hierarchical bayes for comparison with the parameter distribution problem, I don't think this is necessarily worth pursuing for the parameter estimation problem.

**Comment by mathematicalmichael** [comment]
I can add pymc3 to the stack pretty easily I believe. They have a binder setup already that I can start with. 

Make sure to pull changes, I’ve made plenty recently:)

**Comment by mathematicalmichael** [comment]
i got the image to build but haven't quite got kernel connecting the way it is supposed to. giving up for now and closing the issue, but eventually `pymc3` will be included in the binder image.
