### ISSUE TITLE
printing + presenting

### ISSUE THREAD

**Issue by mathematicalmichael** [mathematicalmichael/jsm19#9]
So... I just got wind earlier today of a job interview (in person) on Monday. 
_Upside: at least I'll already be dressed up._

So, with that said, @yentyu, could you post here the details of when/where our presentation is? I would like to show up if it is possible. interview should be over by early afternoon. 

I will have the print in your office by tomorrow afternoon at the absolute latest.

**Comment by yentyu** [comment]
Your traditional poster presentation is scheduled for Session 256 on Monday, 7/29/2019, beginning at 2:00 PM in the Colorado Convention Center, Hall C. Your Poster Number is 86. Details about this session and the entire program are available at

 

https://ww2.amstat.org/meetings/jsm/2019/onlineprogram/index.cfm

 

Please read this entire email, as it contains important information you will need to know prior to arriving.


PRESENTATION INFORMATION

·         Poster Set-Up and Removal: Traditional posters must be set up and removed at the times below. Any poster materials not picked up during your specified removal time will be thrown away. 

      Session Time                          Poster Set-Up                        Poster Removal
10:30 am – 12:20 pm                    9:00 am – 10:25 am                12:20 pm – 12:45 pm
2:00 pm – 3:50 pm                        12:45 pm – 1:55 pm                3:50 pm – 4:30 pm
